import mongoose, { Schema, model, models } from 'mongoose';

const JuniorAdmissionSchema = new Schema({
  surname: { type: String, required: true },
  otherNames: { type: String, required: true },
  dateOfBirth: String,
  sex: String,
  nationality: String,
  state: String,
  homeTown: String,
  lga: String,
  religion: String,
  positionInFamily: String,
  foodAllergy: String,
  drugAllergy: String,
  exclusiveBreastfeeding: String,
  noWater: String,
  immunizationCompleted: String,
  anyReaction: String,
  levelOfSchooling: String,
  parentSurname: String,
  parentOtherNames: String,
  fatherSignature: String,
  fatherPhone: String,
  motherSignature: String,
  motherPhone: String,
  officeAddress: String,
  residentialAddress: String,
  parentsOccupation: String,
  contactPerson: String,
  medicalHistory: String,
  medicalPractitioner: String,
  paymentReference: String,
  paymentStatus: { type: String, default: 'pending' },
  passportPhoto: String,
  examDate: Date,
  submittedAt: { type: Date, default: Date.now },
}, { timestamps: true });

const SeniorAdmissionSchema = new Schema({
  surname: { type: String, required: true },
  otherNames: { type: String, required: true },
  dateOfBirth: String,
  sex: String,
  nationality: String,
  state: String,
  homeTown: String,
  lga: String,
  religion: String,
  language: String,
  schoolLastAttended: String,
  classCompleted: String,
  parentSurname: String,
  parentOtherNames: String,
  relationshipToChild: String,
  parentSignature: String,
  fatherPhone: String,
  motherPhone: String,
  officeAddress: String,
  contactAddress: String,
  residentialAddress: String,
  medicalHistory: String,
  medicalPractitioner: String,
  paymentReference: String,
  paymentStatus: { type: String, default: 'pending' },
  passportPhoto: String,
  submittedAt: { type: Date, default: Date.now },
}, { timestamps: true });

export const JuniorAdmission = models.JuniorAdmission || model('JuniorAdmission', JuniorAdmissionSchema);
export const SeniorAdmission = models.SeniorAdmission || model('SeniorAdmission', SeniorAdmissionSchema);
